### PR TITLE
Fix race condition when initializing node integration

### LINKED ISSUE #789: add/remove iframe cause memory leak
from version 0.19.0 , atom default  binding to all iframes in pages. if add/remove iframe in one page lead to memory leak!

code : 

void AtomRendererClient::WillReleaseScriptContext(
    blink::WebFrame* frame,
    v8::Handle<v8::Context> context,
    int world_id) {

.........
.........
  // Notice that we are not disposing the environment object here, because there
  // may still be pending uv operations in the uv loop, and when they got done
  // they would be needing the original environment.
  // So we are leaking the environment object here, just like Chrome leaking the
  // memory :) . Since it's only leaked when refreshing or unloading, so as long
  // as we make sure renderer process is restared then the memory would not be
  // leaked.
  //env->Dispose();
.........
.........

}

### LINKED ISSUE #894: Having multiple JavaScript contexts causes a race condition in uv event loop handling
I'm experiencing a problem where, intermittently, `setImmediate` stops working -- its callback is not called.  If `setImmediate` is called again, repeatedly, none of the callbacks are called.  They are not called until some other node.js callback runs, such as `fs.readFile`, which flushes them all out.

The problem also happens with `process.nextTick`, but it seems to reproduce more readily with `setImmediate`.

The problem might be Windows only, as I haven't seen it on other OS's.

I debugged the problem on Windows, and I think I largely understand what's breaking.

The UV event loop integration in `NodeBindings` expects the "embed" thread to block on the UV event loop, and when something happens, it wakes up the main thread, and waits until the main thread has finished before blocking on the UV event loop again.  The interaction between the two threads is governed by the `NodeBindings::embed_sem_` semaphore.  The semaphore is initially 0.  `NodeBindings::UvRunOnce` increments it, and `NodeBindings::EmbedThreadRunner` decrements it.  `UvRunOnce` is called from `NodeBindings::RunMessageLoop`, which gets the cycle started.

Unfortunately, when there is more than one JavaScript context, `AtomRendererClient::DidCreateScriptContext` calls `NodeBindings::RunMessageLoop` more than once, which allows the semaphore to increase arbitrarily, and allows the embed thread to run while the main thread is calling `uv_run`.

I *think* this isn't supposed to happen, so we don't need to know any more to implement a fix.

That said, I spent a lot of time instrumenting and debugging the program, so I'll also explain what I think is going on.

For setImmediate, the important thing is that `AtomBindings::ActivateUVLoop` works.  `ActivateUVLoop` runs on the main thread and works by calling `uv_async_send`, which on Windows, posts a packet to the run loop's IO Completion Port.  This packet is dequeued (and requeued) in `NodeBindingsWin::PollEvents`.  Here's what's supposed to happen next:

1. [embed] Embed thread wakes up the main thread, then blocks on the semaphore.
2. [main] `UvRunOnce` calls `uv_run` with flags `UV_RUN_ONCE | UV_RUN_NOWAIT`.
3. [main] `uv_run` calls `uv_poll_ex`.
4. [main] `uv_poll_ex` dequeues the async req.
5. [main] `uv_poll_ex` inserts the async req into `loop->pending_reqs_tail`.
6. [main] `uv_run` returns.
7. [main] Main thread signals embed thread to start again.
8. [embed] `PollEvents` notices that `uv_loop_->pending_reqs_tail` is non-NULL, so it immediately returns (without checking the IOCP).
9. [embed] Embed thread wakes up the main thread, then blocks on the semaphore.
10. [main] `UvRunOnce` calls `uv_run` again with the same flags.
11. [main] `uv_run` calls `uv_process_reqs`, which calls `uv_process_async_wakeup_req`, which calls `AtomBindings::OnCallNextTick`.
12. [main] `AtomBindings::OnCallNextTick` resets `self->pending_next_ticks_`.

In the failure I'm seeing, I think step 8 happens between steps 4 and 5.  `PollEvents` decides that it should block on the IOCP, but when it does block, there is no packet to dequeue.  The async req sits unexamined in the `loop->pending_reqs_tail` queue, because the embed thread isn't waking up the main thread.  Later calls to `AtomBindings::ActivateUVLoop` do nothing because `self->pending_next_ticks_` is non-empty.

Here's the test case I have:

package.json:

    {
        "name": "AtomImmediateBug",
        "version": "0.1.0",
        "main": "main.js"
    }

main.js:

    var app = require("app");
    var BrowserWindow = require("browser-window");
    var bw = null;
    app.on("ready", function() {
        bw = new BrowserWindow({ width: 300, height: 300 });
        bw.loadUrl("file://" + __dirname + "/index.html");
        bw.openDevTools();
    });

index.html:

    <html>
        <head>
            <script>
                console.log("index.html")
                var clickCount = 0;
                var counter = 0;
                function stress() {
                    console.log("click " + ++clickCount);
                    setImmediate(stressContinue);
                }
                function stressContinue() {
                    counter++;
                    if (counter >= 5) {
                        console.log("DONE");
                        counter = 0;
                    } else {
                        setImmediate(stressContinue);
                    }
                }
            </script>
        </head>
        <body>
        <a href="javascript:stress();">Stress</a>
            
            <iframe src="index2.html"></iframe>
            <iframe src="index2.html"></iframe>
            <iframe src="index2.html"></iframe>
            <iframe src="index2.html"></iframe>
        </body>
    </html>

index2.html:

    <html>
        <head>
            <script>console.log("index2.html")</script>
        </head>
        <body>
        </body>
    </html>

Click the Stress link until `DONE` stops appearing.  For me, it usually broke in under 10 clicks.

I tested this program with v0.19.4 atom-shell on 32-bit Windows 7 Ultimate SP1.  I ran Windows in a 4-core VM in VirtualBox 4.3.10 on a 4-core/8-thread 64-bit Ubuntu machine.

Adding a sleep between steps 4 and 5 above might also help.  At one point, it helped enormously when the test case used `process.nextTick` instead of `setImmediate`.

Here's the `vendor/node` patch that does that:

    diff --git a/deps/uv/src/win/core.c b/deps/uv/src/win/core.c
    index c9e4c88..0ff80a4 100644
    --- a/deps/uv/src/win/core.c
    +++ b/deps/uv/src/win/core.c
    @@ -310,6 +310,7 @@ static void uv_poll(uv_loop_t* loop, DWORD timeout) {
                                 timeout);
    
       if (overlapped) {
    +    Sleep(300);
         /* Package was dequeued */
         req = uv_overlapped_to_req(overlapped);
         uv_insert_pending_req(loop, req);
    @@ -346,6 +347,7 @@ static void uv_poll_ex(uv_loop_t* loop, DWORD timeout) {
    
       if (success) {
         for (i = 0; i < count; i++) {
    +      Sleep(300);
           /* Package was dequeued */
           req = uv_overlapped_to_req(overlappeds[i].lpOverlapped);
           uv_insert_pending_req(loop, req);

### LINKED ISSUE #1028: Can't require node modules in renderer process in v0.20.6 without a refresh
Our app with v0.20.6 is crashing on first startup, but refreshing the Window fixes it. It appears to be related to module paths:

```
FIRST LOAD:
[  
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/renderer/lib/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/renderer/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/node_modules",
  "/private/var/folders/_c/node_modules",
  "/private/var/folders/node_modules",
  "/private/var/node_modules",
  "/private/node_modules",
  "/node_modules",
  "/Users/paul/.node_modules",
  "/Users/paul/.node_libraries",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Frameworks/Slack Helper.app/Contents/lib/node",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/renderer/api/lib",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/app",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/common/api/lib"
]

AFTER REFRESH:

[  
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/renderer/lib/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/renderer/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/node_modules",
  "/private/var/folders/_c/node_modules",
  "/private/var/folders/node_modules",
  "/private/var/node_modules",
  "/private/node_modules",
  "/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/app/static/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/app/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/node_modules",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/node_modules",
  "/private/var/folders/_c/node_modules",
  "/private/var/folders/node_modules",
  "/private/var/node_modules",
  "/private/node_modules",
  "/node_modules",
  "/Users/paul/.node_modules",
  "/Users/paul/.node_libraries",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Frameworks/Slack Helper.app/Contents/lib/node",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/renderer/api/lib",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/app",
  "/private/var/folders/_c/hwfdpfg168s0tl7dlqzfrf_h0000gn/T/slack-build/Slack.app/Contents/Resources/atom/common/api/lib"
]
```

Note that once we issue a refresh, `$TMPDIR/slack-build/Slack.app/Contents/Resources/app/node_modules` is now in the path list, whereas on first load, it's *not*.

### PR DESCRIPTION
**Pull request by zcbenz**
1. The custom atom-shell APIs are now injected before we initialize in JavaScript, making the JavaScript code more clear.
2. Lots of cleanups of the node integration code.
3. We now do not initialize node integration in `iframe`s, because you can either use `<webview>` instead, or just access node integration in parent frame. This greatly simplified the node integration code in renderer process, also fixes #894 and fixes #789.
4. Don't deal with browser messages when the document object is not ready, fixe #1028 and fixe #1038.

### CODE REVIEW

**Comment by zcbenz** [comment]
@paulcbetts Can you test if this fixes #1028 for your?

**Comment by paulcbetts** [comment]
@zcbenz no dice :( Patched init.js:

```javascript
  global.wtf = [];
  wtf.push(window.location.href);
  wtf.push(window.location.protocol);

  if (nodeIntegration === 'true' || nodeIntegration === 'all' || nodeIntegration === 'except-iframe' || nodeIntegration === 'manual-enable-iframe') {
 /* ... */
```

```
>> navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Slack/0.5.1-d32528a Chrome/39.0.2171.65 AtomShell/0.20.7 Safari/537.36"

global.wtf
>> ["about:blank", "about:"]
```

**Comment by zcbenz** [comment]
@paulcbetts Can you provide a minimal app that shows this problem? I wonder if it only occurs when we used some APIs in code, because I never encountered a similar problem in Atom editor.

**Comment by paulcbetts** [comment]
@zcbenz I can work on that, yeah - I'm out today but I'll have a look tonight

**Comment by zcbenz** [comment]
@paulcbetts Cool, thanks!

**Comment by zcbenz** [comment]
@paulcbetts #1028 should have been fixed by 0bcc9b7, can you have a test of this branch?

**Comment by paulcbetts** [comment]
Works perfectly! :tada:

**Pull request merged**
