### PR TITLE
Electron icon

### PR DESCRIPTION
**Pull request by simurai**
This PR is on top of https://github.com/atom/atom-shell/pull/1389 and replaces the Mac and Win icons.

I probably tweak it a bit more at some point. But in case you need it already now, here a first version.

screen shot 2015-04-17 at 12 21 34 am

I guess the icon files itself should also be renamed? Maybe `atom.icns` -> `icon.icns`. Then it's just generic and not project related.

### CODE REVIEW

**Comment by steelbrain** [comment]
Why not the Linux Icons?

**Comment by simurai** [comment]
Currently there are no Linux icons, but I could add them too if needed? /cc @zcbenz

**Comment by steelbrain** [comment]
I would personally give you some chocolate if you do so. :chocolate_bar:

**Comment by kevinsawicki** [comment]
> Currently there are no Linux icons, but I could add them too if needed?

I definitely think we should do this but I think it can be done in a separate pull request.

Merging this, awesome work! looks great :+1:

**Comment by YuriSolovyov** [comment]
Does it stay readable on smaller sizes (16 / 32 / 48 pixels)?

**Comment by thomasjo** [comment]
Nice work @simurai! Looks really, really nice.



> Does it stay readable on smaller sizes (16 / 32 / 48 pixels)?

Yes.

**Comment by simurai** [comment]
Yeah, they are all individual graphics. `16px` gets a bit mushy. And the lines could be a bit thicker. Something for a next revision.

screen shot 2015-04-17 at 8 40 52 am

**Comment by philipgiuliani** [comment]
Really cool icon :)

**Pull request merged**
