### PR TITLE
mac: Dynamically enable accessibility based on VoiceOver status

### PR DESCRIPTION
**Pull request by theojulienne**
This PR adds extremely basic support for accessibility on OS X using VoiceOver by enabling chromium accessibility when VoiceOver is active.

Previously, any usage of VoiceOver was broken due to a patch to force Text-to-Speech to use Cmd+C to speak the selected text instead of the window title. For users using accessibility, this trapped them in the window with no child accessibility elements, giving an experience something like:
atom-shell-no-accessibility

This patch is two-fold:
 * VoiceOver is detected, and the chromium accessibility feature is enabled and disabled based on this status. A similar approach to that used in Chromium itself is used for this.
 * The TTS hack is modified to leave the chromium accessibility tree and the close/minimise/maximise buttons (but not the window title) as children of the window, rather than removing them completely.

The final result is that accessibility implementation on mac is now left up the standard HTML/web content accessibility features:
atom-shell-partial-accessibility gif

### CODE REVIEW

**Comment by theojulienne** [comment]
Relevant to atom/atom#1691, this fixes the atom-shell part of the issue (but does nothing to make Atom itself any more accessible).

**Comment by paulcbetts** [comment]
Can you ensure that this works on Windows as well with [NVDA](http://www.nvaccess.org/)?

**Comment by theojulienne** [comment]
This currently only touches Mac accessibility in 2 files that are Mac-only, I guess a completely separate PR would be needed to make similar changes on other platforms.

**Comment by zcbenz** [comment]
This is incredible, thanks!

**Pull request merged**
