### PR TITLE
webContents: event to detect status of requested resource

### PR DESCRIPTION
**Pull request by deepak1556**
#1253 , can probably be fixed with this event. Also if needed can give `resource_type` as payload from the list [here](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/common/resource_type.h&cl=GROK&ct=xref_jump_to_def&l=13&gsn=ResourceType) , some ugly switch case on coffee side will do. any thoughts ?

### CODE REVIEW

**Comment by zcbenz** [comment]
Current implementation looks good to me, thanks!

**Comment by nistvan86** [comment]
Can this be modified to include response headers? Or in this state no actual network traffic occurs in Chromium? I would expect at least a HEAD request is being done to check the cache state.

I would like to use this to catch download events, but since this event fires for other resource requests as well, and doesn't state that Chromium will not handle the event internally, i can't be sure if i should check the URL manually for a downloadable resource or not. If the response headers would be there, i could check for eg. the presence of the `Content-Disposition` header and assume that Chromium will throw away this request in a later stage.

**Comment by deepak1556** [comment]
@nistvan86 will this help now https://github.com/atom/electron/pull/1604 ?

**Comment by nistvan86** [comment]
Yes, it definitely helps, thanks! I've answered there aswell.

**Comment by deepak1556** [comment]
nope i dont have one.

**Pull request merged**
