### PR TITLE
test for ignoreCertificateError

### PR DESCRIPTION
**Pull request by deepak1556**
the test should pass with the changes to brightray :)

### CODE REVIEW

**Comment by zcbenz** [comment]
The test should fail before we include the brightray change, I guess `--ignore-certificate-errors` is actually working and #1221 is caused by something else?

**Comment by deepak1556** [comment]
Sorry i missed to test without the change to brightray. Maybe @kwindla can give a small test case which fails. We can still add `AllowCertError` method to brightray which would warn if cert error occurs.

**Comment by kwindla** [comment]
Test case is here: https://github.com/kwindla/test-ignore-cert-errors

I apologize for not implementing this as a pull request. It was faster to give you a standalone test case.

The issue seems to be with certificates that have an empty Common Name field, rather than with all self-signed certificates (which was what I originally assumed).

**Comment by mark-hahn** [comment]
> --ignore-certificate-errors

I assume this is meant to me used at the command-line when starting atom-shell.  Is there a way to do it in a webview tag?  I'm getting an exception right now.

**Comment by zcbenz** [comment]
Though the `ignore-certificate-errors` is actually working, I think it is fine to have a test case for it, thanks!

**Comment by zcbenz** [comment]
@mark-hahn Currently the networking parameters have to be global, so if you want to enable it for webview tag, you have to enable it for the whole app.

**Comment by mark-hahn** [comment]
Thanks.  I'll see if I can talk the Atom team into doing it.

**Pull request merged**
