### PR TITLE
Update README to replace node.js with io.js

### PR DESCRIPTION
**Pull request by paulyoung**
Relates to #1108.

### CODE REVIEW

**Comment by zcbenz** [comment]
Thanks!

**Comment by paulyoung** [comment]
@zcbenz just a heads up, I received this email afterwards:

screen shot 2015-03-05 at 2 03 39 pm

Not sure if you aware that this kind of thing was happening.

**Comment by zcbenz** [comment]
@paulyoung I think most of the team have received something like that.

**Comment by bwin** [comment]
Yeah, everybody receives that.

**Pull request merged**
