### PR TITLE
Add API to enumerate external displays in screen module

### LINKED ISSUE #780: Add support for choosing in which screen (if more than 1) to show the app
It's more and more common to find desktops with two or even three screens. Make Atom Shell be able to detect such cases and allow the developer to show the app in a certain screen.

### PR DESCRIPTION
**Pull request by zcbenz**
Fixes #780.

```markdown

## Event: display-added

* `event` Event
* `newDisplay` Object

Emitted when `newDisplay` has been added.

## Event: display-removed

* `event` Event
* `oldDisplay` Object

Emitted when `oldDisplay` has been removed.

## Event: display-metrics-changed

* `event` Event
* `display` Object
* `changedMetricts` Array

Emitted when a `display` has one or more metrics changed, `changedMetricts` is
an array of strings that describe the changes. Possible changes are `bounds`,
`workArea`, `scaleFactor` and `rotation`.

## screen.getAllDisplays()

Returns an array of displays that are currently available.

## screen.getDisplayNearestPoint(point)

* `rect` Object
  * `x` Integer
  * `y` Integer

Returns the display nearest the specified point.

## screen.getDisplayMatching(rect)

* `rect` Object
  * `x` Integer
  * `y` Integer
  * `width` Integer
  * `height` Integer

Returns the display that most closely intersects the provided bounds.
```

Another example of creating a window in the external display:

```javascript
var app = require('app');
var BrowserWindow = require('browser-window');

var mainWindow;

app.on('ready', function() {
  var screen = require('screen');
  var displays = screen.getAllDisplays();
  var externalDisplay = null;
  for (var i in displays) {
    if (displays[i].bounds.x > 0 || displays[i].bounds.y > 0) {
      externalDisplay = displays[i];
      break;
    }
  }

  if (externalDisplay) {
    mainWindow = new BrowserWindow({
      x: externalDisplay.bounds.x + 50,
      y: externalDisplay.bounds.y + 50,
    });
  }
});
```

### CODE REVIEW

**Comment by bwin** [comment]
Sounds good!

**Comment by iamdriz** [comment]
Is this in a release? I just downloaded 0.20.6 but I get undefined function for `getAllDisplays()` so I'll presume it's not been properly released yet? Thanks for this though :) really excited to try it soon!

**Comment by zcbenz** [comment]
It will be in next release.

**Comment by iamdriz** [comment]
Sweet! Thank you so so much for getting this added so quickly. Really appreciated!

**Pull request merged**
