### PR TITLE
Upgrade to Chrome 40

### PR DESCRIPTION
**Pull request by zcbenz**
Merge this after there is a stable release of Chrome 40.

### CODE REVIEW

**Comment by mark-hahn** [comment]
Will this fix the webview problem also?  Is there an easy way for me to build atom using this so I can test the webview?

**Comment by paulcbetts** [comment]
@zcbenz Can you `git push` all your submodules? `libchromiumcontent` is pinned to a commit that isn't up on GitHub atm

**Comment by zcbenz** [comment]
Chrome 40 becomes stable today, I'll finish this PR.

@mark-hahn The [change](https://chromium.googlesource.com/chromium/src/+/a95fef4232d44e8f102e20afe0c49009742f4857) I need to fix the `<webivew>` crash is not in Chrome40 yet, I'm afraid we have to wait until Chrome41, but I'll still have a try.

**Comment by zcbenz** [comment]
Latest `nan` is now using `NODE_MODULE_VERSION` to determine the V8 version to support, in order to be compatible with `nan` we need to pick a `NODE_MODULE_VERSION` value very carefully.

**Comment by zcbenz** [comment]
Currently blocked by compatibility with `nan`: https://github.com/rvagg/nan/issues/226.

**Comment by paulcbetts** [comment]
Would it be worth it to forget about the io.js migration for this PR? It seems like it's going to bust a ton of native modules right now since it's super new. Or will Chrome 40's version of V8 bust them anyways, so who cares?

**Comment by zcbenz** [comment]
The problem is Atom uses lots of native modules and I have to make Atom work with Chrome 40. Anyway I have just uploaded a [modified version of nan](https://github.com/atom/node-runas/commit/cc71cacd2635ec92ac2653d173b16b8555f86990) to work around it.

**Pull request merged**
