### PR TITLE
 fs.read empty files from asar archive

### LINKED ISSUE #1257: Read empty file result in error
Hi,

if i am loading an empty file via fs.readFileSync(...) or fs.readFile(...) it will result in an error.

I have following code:

```
var fs = require('fs');
logger.error('try get empty file');
try {
    var content = fs.readFileSync(__dirname + '/blocks/test/0.1/style.less');
    logger.error('no error');
}
catch (ex) {
    logger.error('catched');
    logger.error(ex);
}
logger.error('finished');
```

the result of the logging (with the readFileSync) will be:

```
Stdout:[2015-03-17 14:58:09.479] [ERROR] Browser - try get empty file

Stdout:[2015-03-17 14:58:09.485] [ERROR] Browser - catched

Stdout:[2015-03-17 14:58:09.486] [ERROR] Browser - [Error: Offset is out of bounds]
Error: Offset is out of bounds
    at Error (native)
    at Object.fs.readSync (fs.js:555:19)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:390:12)
    at .../Atom.app/Contents/Resources/app.asar/app.js:31:26
    at Object.<anonymous> (.../Atom.app/Contents/Resources/app.asar/app.js:39:2)
    at Module._compile (module.js:475:26)
    at Object.Module._extensions..js (module.js:493:10)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Object.<anonymous> (.../Atom.app/Contents/Resources/atom/browser/lib/init.js:116:10)
```

If i do this asynchronously (readFile) the readFile's callback will not be populated with the error object, instead the error is passed to the frontend and is shown to the user via a error popup

The problem occurs, because the style.less which i try to load is empty. 
Therefore the buffer in common/lib/asar.coffee line: (231) and (260):
```
buffer = new Buffer(info.size);
```
will be of size 0 because info.size is 0.

Maybe you could prevent the error by checking if the size is greater than 0

### PR DESCRIPTION
**Pull request by deepak1556**
fixes #1257

### CODE REVIEW

**Comment by deepak1556** [comment]
went by this fix as we dont create a buffer with size greater than offset for size=0 https://github.com/iojs/io.js/blob/v1.x/lib/fs.js#L272 or should we do that perhaps ?

**Comment by zcbenz** [comment]
We should follow io.js's way, otherwise we are still not able to read empty file.

**Comment by zcbenz** [comment]
I think we can just return an empty Buffer when size is 0?

**Comment by deepak1556** [comment]
yeah i should have done that , mistook https://github.com/iojs/io.js/blob/v1.x/lib/fs.js#L432 to not trust size which shouldnt be the case of asar as its confirmed in the header, sorry..

**Comment by zcbenz** [comment]
Thanks!

**Pull request merged**
